### PR TITLE
fixbug: save obj file streamwriter has no close

### PR DESCRIPTION
**Pull request by jackletter**

### CODE REVIEW

**Comment by vpenades** [comment]
Thanks for your bugfix, but in its current state I cannot merge it, because it does not follow good programming practices.

streams need to be closed/disposed by the same function that  opened them to ensure the stream is properly handled.

So the right way to do it is to expand the lambda funciont and dispose the stream after having called the _GetGeometryContent method.

**Comment by jackletter** [comment]
@vpenades yes, you are wright, but the bug need fix, otherwise the *.obj file is incomplete

**Comment by vpenades** [comment]
I'll give a look at the wavefront and figure out another way of fixing this

**Comment by vpenades** [comment]
I've been able to fix it on my end, so this pull request is no longer neccesary.

Thanks for hilighting the issue.

**Pull request closed without merging**
